# Master settings file for repository


# This entry for google-as-template details
google_settings:  # First three lines are based on your project
  project_dir: 'enter_the_key_for_project_folder_here'
  project_name: 'Enter the name of your project here'
  script_name: 'Enter the name of your script file here (will be created)'
  project_tz: 'America/Chicago'  # From this line down, modifiable defaults
  local_script_dir: 'scripts'
  local_settings: 'settings/local_settings.yml'
  store_dir: '.credentials'
  credentials_file: 'credentials.json'
  credentials_store: 'token.pickle'
  scopes:  # If these are changed, repeat flow by deleting token.pickle
    - 'https://www.googleapis.com/auth/drive'
    - 'https://www.googleapis.com/auth/script.projects'
    - 'https://www.googleapis.com/auth/spreadsheets'
  service_versions:
    script: 'v1'
    drive: 'v3'
  refresh_ttl: 365  # seconds tokens are invalid prior to expiration

# Log settings are called outside of the main script
log_settings:
  format: '%(asctime)s %(hostname)s %(jobname)s: [%(levelname)s] %(message)s'
  date_format: '%b %d %H:%M:%S'
  hostname: mn_laptop  # Change this for different hosts
  local_level: 10  # set to int level for local logging (60=none, 50=critical, 10=debug)
  xremote_address:  # To enable remote logging, remove the x at the front of the label
    - loggingaddress.com  # replace with your log destination
    - 00000  # replace with your port

# Other entries for the specific repository are possible here